### ISSUE TITLE
Cent OS helper node image cannot access repos anymore

### ISSUE THREAD

**Issue by aditya1arvind** [borball/ocp-baremetal-ipi#2]
https://forketyfork.medium.com/centos-8-no-urls-in-mirrorlist-error-3f87c3466faa

affected by this issue.

sudo sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*

inside /etc/yum.repos.d fixes it.

**Comment by borball** [comment]
Fixed. used centos8stream instead of centos8.
